Repository Paratii-Video/paratii-portal, pull requests merged in 2018-02, with the labels that each got.

#148 404 page
  src/scripts/components/pages/NotFound.js
Labels: enhancement

#147 Uploader ui - video list
  .stylelintignore
  src/scripts/components/VideoForm.js
  src/scripts/components/VideoList.js
  src/scripts/components/VideoListItem.js
  src/scripts/components/foundations/Text.js
  src/scripts/components/foundations/base/Sizes.js
  src/scripts/components/foundations/base/Themes.js
  src/scripts/components/foundations/base/Typography.js
  src/scripts/components/foundations/svgs/MainSvg.js
  src/scripts/components/structures/Card.js
  src/scripts/components/widgets/FilesUploader.js
  src/scripts/components/widgets/PTIGuide.js
  src/scripts/components/widgets/VideoForm/VideoProgress.js
  src/scripts/components/widgets/VideoForm/VideoProgressBar.js
  src/scripts/components/widgets/forms/RadioCheck.js
  src/scripts/components/widgets/forms/TextField.js
  src/scripts/components/widgets/forms/TextareaField.js
  src/scripts/containers/VideoManagerContainer.js
  yarn.lock
Labels: uploader

#171 163 modal
  .circleci/images/primary/Dockerfile
  config/development.json
  karma.conf.js
  parity-config.toml
  src/scripts/components/App.js
  src/scripts/components/VideoForm.js
  src/scripts/components/VideoListItem.js
  src/scripts/components/foundations/Button.js
  src/scripts/components/foundations/Title.js
  src/scripts/components/foundations/base/Themes.js
  src/scripts/components/foundations/base/Typography.js
  src/scripts/components/foundations/svgs/MainSvg.js
  src/scripts/components/pages/Home.js
  src/scripts/components/structures/header/MainHeader.js
  src/scripts/components/widgets/forms/RadioCheck.js
  src/scripts/components/widgets/modals/Modal.js
  src/scripts/components/widgets/modals/ModalStake.js
  src/scripts/utils/AppUtils.js
Labels: uploader

#187 185 - indicate which video is selected in uploader
  src/scripts/components/VideoList.js
  src/scripts/components/VideoListItem.js
  src/scripts/components/foundations/base/Colors.js
  src/scripts/components/foundations/base/Themes.js
Labels: uploader

#198 Design.Portal Uploader corrections #184
  package-lock.json
  src/assets/svg/card-bg.svg
  src/index.html
  src/scripts/components/App.js
  src/scripts/components/VideoForm.js
  src/scripts/components/Wallet.js
  src/scripts/components/foundations/Button.js
  src/scripts/components/foundations/Text.js
  src/scripts/components/foundations/Title.js
  src/scripts/components/foundations/base/Sizes.js
  src/scripts/components/foundations/base/Themes.js
  src/scripts/components/foundations/base/Typography.js
  src/scripts/components/foundations/svgs/FilesUploaderSvg.js
  src/scripts/components/foundations/svgs/MainSvg.js
  src/scripts/components/foundations/svgs/PTIGuideSvg.js
  src/scripts/components/pages/Home.js
  src/scripts/components/pages/NotFound.js
  src/scripts/components/structures/Card.js
  src/scripts/components/structures/footer/MainFooter.js
  src/scripts/components/structures/header/MainHeader.js
  src/scripts/components/templates/MainTemplate.js
  src/scripts/components/widgets/FilesUploader.js
  src/scripts/components/widgets/PTIGuide.js
  src/scripts/components/widgets/RedeemVoucher.js
  src/scripts/components/widgets/VideoForm/VideoProgress.js
  src/scripts/components/widgets/VideoForm/VideoProgressBar.js
  src/scripts/components/widgets/forms/RadioCheck.js
  src/scripts/components/widgets/modals/Modal.js
  src/scripts/containers/VideoManagerContainer.js
  src/styles/app.scss
  src/styles/reset.scss
  yarn.lock
Labels: uploader

#250 Uploader ui
  src/scripts/actions/VideoActions.js
  src/scripts/components/Play.js
Labels: uploader

#257 label on the forms cover the input things - fixed #246
  src/scripts/components/pages/Voucher.js
  src/scripts/components/widgets/forms/TextField.js
  src/scripts/components/widgets/forms/TextareaField.js
Labels: bug, uploader
