Repository Paratii-Video/paratii-portal, pull requests merged in 2018-03, with the labels that each got.

#280 Main loader
  package-lock.json
  src/assets/img/paratii-loader.gif
  src/index.html
  src/scripts/components/templates/MainTemplate.js
Labels: uploader

#291 componentWillReceiveProps to textareafield textarea field
  package-lock.json
  src/scripts/components/VideoForm.js
  src/scripts/components/widgets/forms/TextField.js
  src/scripts/components/widgets/forms/TextareaField.js
  src/scripts/containers/VideoManagerContainer.js
Labels: uploader

#292 Textarea and Play embed size
  src/scripts/components/Play.js
  src/scripts/components/VideoForm.js
  src/scripts/components/widgets/forms/TextareaField.js
Labels: bug, uploader

#307 Renaming navigation items
  package-lock.json
  src/scripts/components/structures/header/MainNavigation.js
Labels: uploader

#309 Fix handle height
  src/scripts/components/widgets/forms/TextareaField.js
Labels: bug, uploader

#312 Loading bars #278 & e ReedemVoucher #310
  package-lock.json
  src/scripts/components/VideoFormInfoBox.js
  src/scripts/components/foundations/base/Themes.js
  src/scripts/components/widgets/RedeemVoucher.js
  src/scripts/components/widgets/VideoForm/VideoProgress.js
  src/scripts/components/widgets/VideoForm/VideoProgressTitle.js
  src/scripts/components/widgets/forms/TextField.js
Labels: uploader

#324 UI fixes and updates
  package-lock.json
  src/scripts/components/Play.js
  src/scripts/components/VideoForm.js
  src/scripts/components/VideoFormInfoBox.js
  src/scripts/components/VideoList.js
  src/scripts/components/VideoListItem.js
  src/scripts/components/foundations/base/Sizes.js
  src/scripts/components/foundations/base/Themes.js
  src/scripts/components/foundations/forms/Input.js
  src/scripts/components/foundations/svgs/MainSvg.js
  src/scripts/components/structures/Card.js
  src/scripts/components/structures/Main.js
  src/scripts/components/structures/footer/MainFooter.js
  src/scripts/components/widgets/FilesUploader.js
  src/scripts/components/widgets/PTIGuide.js
  src/scripts/components/widgets/RedeemVoucher.js
  src/scripts/components/widgets/VideoForm/VideoProgressBar.js
  src/scripts/containers/VideoManagerContainer.js
  src/server/routes/embed.js
  src/server/views/index.hbs
  src/styles/app.scss
  src/styles/embed/index.scss
Labels: uploader

#301 Feature/refactor moda (=the staking modal) [do not merge yet]
  package-lock.json
  src/scripts/actions/ModalActions.js
  src/scripts/components/App.js
  src/scripts/components/VideoForm.js
  src/scripts/components/VideoList.js
  src/scripts/components/foundations/base/Themes.js
  src/scripts/components/widgets/modals/Modal.js
  src/scripts/components/widgets/modals/ModalStake.js
  src/scripts/constants/ActionConstants.js
  src/scripts/containers/ModalContainer.js
  src/scripts/containers/ModalStakeContainer.js
  src/scripts/containers/VideoFormContainer.js
  src/scripts/containers/VideoFormInfoBoxContainer.js
  src/scripts/records/ModalRecord.js
  src/scripts/reducers/ModalReducer.js
  src/scripts/reducers/index.js
  src/scripts/selectors/UploaderSelectors.js
Labels: bug, uploader

#361 67 player page
  package-lock.json
  src/scripts/components/Play.js
  src/scripts/components/foundations/Text.js
  src/scripts/components/foundations/base/Themes.js
  src/scripts/components/foundations/svgs/MainSvg.js
  src/scripts/components/widgets/MainHeaderLogo.js
  src/scripts/components/widgets/SearchInput.js
  src/scripts/types/ApplicationTypes.js
  src/styles/app.scss
Labels: uploader

#380 Hiding elements
  package-lock.json
  src/scripts/components/Play.js
  src/scripts/components/VideoFormInfoBox.js
  src/scripts/components/VideoList.js
Labels: uploader

#383 VideoListItem status #365
  src/scripts/components/VideoListItem.js
Labels: uploader

#390 Show uploading and transcoding failed on VideoListItem #387
  src/scripts/components/VideoListItem.js
Labels: uploader

#379 [WIP] - 373 - reduce controls height
  src/scripts/components/VideoOverlay.js
  src/scripts/constants/UIConstants.js
Labels: optimization

#396 391 videolistitem status
  src/scripts/actions/UploaderActions.js
  src/scripts/components/VideoListItem.js
  src/scripts/reducers/VideosReducer.js
Labels: bug, uploader

#405 If no title is given, we should show use the filename as the title #393
  src/scripts/components/Play.js
Labels: feature, uploader

#411 Meta Viewport for mobile and mobile simples navigation
  src/scripts/components/foundations/base/Sizes.js
  src/scripts/components/foundations/svgs/MainSvg.js
  src/scripts/components/structures/Card.js
  src/scripts/components/structures/Main.js
  src/scripts/components/structures/header/MainHeader.js
  src/scripts/components/structures/header/MainNavigation.js
  src/server/views/index.hbs
Labels: uploader

#415 Player Controls Ui - hide controls
  src/scripts/components/PlayerControls.js
Labels: bug, player-ui
